COMPILER = 'g++'

BOTAN_INCLUDE = '/usr/local/include/botan-2'
BOTAN_LIB = '/usr/local/lib/libbotan-2.a'

TEST_FILE = 'challenge2_test.h'
TEST_RUNNER_NAME = 'runner'

desc "Create CxxTest"
task :create_test do
    `cxxtestgen --error-printer -o #{TEST_RUNNER_NAME}.cpp #{TEST_FILE}`
end

desc "Compile tests"
task :build do
    `#{COMPILER} -I#{BOTAN_INCLUDE} -o #{TEST_RUNNER_NAME} #{TEST_RUNNER_NAME}.cpp #{BOTAN_LIB}`
end

desc "Run tests"
task :test do
    puts `./#{TEST_RUNNER_NAME}`
end
